### ISSUE TITLE
Fazer a relação em Caxias do Sul entre inscrição imobiliária e endereço, para termos um exemplo.

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/LIXO-digital-preservation-BR#12]

**Comment by ThierryAJean** [comment]
Peter sugere que Igor e Carlos, talvez com ajuda do Claiton, possa fazer estas operações de "join"

**Comment by ThierryAJean** [comment]
@0e1 Vai se envolver para produzir o Join entre tabela  de endereços e lotes.

**Comment by 0e1** [comment]
A operação de join entre um layer e o seu respectivo layer de cadastro (seguindo as especificações em https://github.com/digital-guard/preserv/blob/main/docs/pt/ftypes.md) já é possível.
Para tal usar `join_column: nome da coluna` no par de layers envolvidos e `make join-nomedolayer`.

**Comment by ThierryAJean** [comment]
@crebollobr Testar e verificar o Yaml
