### ISSUE TITLE
Florianopolis - Makefile

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/LIXO-digital-preservation-BR#14]
Florianópolis
Importar csv: com problema, layer duplicado e erro no formato tele

O arquivo csv deve ser formado dos e ter \r\n no final da linha

```
ingest2=# \d pk59_001_p1_cadvia
              Foreign table "public.pk59_001_p1_cadvia"
     Column     | Type | Collation | Nullable | Default | FDW options
----------------+------+-----------+----------+---------+-------------
 cd_atrb        | text |           |          |         |
 nm_atrb        | text |           |          |         |
 nm_descricao\r | text |           |          |         |
Server: files
FDW options: (filename '/tmp/sandbox/_pk59_001/atributo_logradouro.csv', format 'csv', header 'true', delimiter ',')
```

ele criou o campo nm_descricao\r com o \r no final

**Comment by ghost** [comment]
Esses dois commits pretendem tratar essa situação:

https://github.com/digital-guard/preserv-BR/commit/b4e6b848eb6da1dadcb9077d6ad5bb05e27419a8
https://github.com/digital-guard/preserv/commit/5b520df7d0e43906d45483fb2e56097061321f21

No arquivo de configuração utilizar como método _csv2unix2utf8_:

`method: csv2unix2utf8`

E indicar a codificação do csv em _csv_encoding_, nos fomatos aceitos pelo _iconv_, por exemplo:

`csv_encoding: iso-8859-15`

**Comment by 0e1** [comment]
Na branch [template_floripa](https://github.com/digital-guard/preserv-BR/tree/template_floripa)  criei o template [make_ref059a.mustache.mk](https://github.com/digital-guard/preserv-BR/blob/template_floripa/src/maketemplates/make_ref059a.mustache.mk) para [_pk59](https://github.com/digital-guard/preserv-BR/tree/main/data/SC/Florianopolis/_pk059), baseado no recente [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SC/Florianopolis/_pk059/make_conf.yaml) adicionado nesse [commit](https://github.com/digital-guard/preserv-BR/commit/7c274f2e26e8aafa881c5e0ec2bb3f09e3768d08).

Alterei o layer _cadvia_ de [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/SC/Florianopolis/_pk059/make_conf.yaml) resultando no [make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/template_floripa/data/SC/Florianopolis/_pk059/make_conf.yaml), para lidar com o arquivo csv que utiliza CRLF, de maneira que ele passe a usar LF.

Testei o funcionamento comentando todos os layers, exceto _cadvia_, e verificando se ocorria a troca de CRLF para LF.

Para os demais layers foram reutilizados os códigos disponíveis no [make_ref027a.mustache.mk](https://github.com/digital-guard/preserv-BR/blob/template_floripa/src/maketemplates/make_ref027a.mustache.mk).
