### ISSUE TITLE
Pato Branco

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/LIXO-digital-preservation-BR#16]
Uma vez que todos os lotes tiverem número de lote e número de quadra pela **tarefa 1**, deve-se usar a planilha `Relatorio_de_numeracao_predial.csv` para atribuir os endereços nos lotes.

**Comment by 0e1** [comment]
Se esse situação necessitar de join, utilizar, em cada par de layers (layer e seu respectivo layer de cadastro):
`join_column: nome_da_coluna_utilizada_para_fazer_join`

**Comment by crebollobr** [comment]
acredito que esteja resolvido
