### ISSUE TITLE
Colocar ogr2ogr  no template make_ref027a.mustache.mk 

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/LIXO-digital-preservation-BR#17]
1) Colocar o ogr2ogr no template make_ref027a.mustache.mk 
{{>common003_shp2pgsql}}
{{>common005_ogr2ogr}}

Porque a mesma cidade tem ogr2ogr e shapefile 

2) Extração mais genérica sem o ponto para extrair gdb, subpasta ou coleção de arquivos

cd $(sandbox);  7z x -y  $(part{{file}}_path) "{{orig_filename}}.*" ; chmod -R a+rx . > /dev/null

cd $(sandbox);  7z x -y  $(part{{file}}_path) "{{orig_filename}}*" ; chmod -R a+rx . > /dev/null

3) ogr2ogr com uma variável a mais opicional {{orig_ext}}

 docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres'     " "/tmp/{{orig_filename}}{{orig_ext}}" {{{orig_tabname}}} -nln $(tabname)

exemplos
orig_ext: .TAB
orig_ext: .gpkg
orig_ext: .xls

**Comment by ppKrauss** [comment]
Alguns exemplos onde usa method e method_ops:

* via em https://github.com/AddressForAll/digital-preservation-BR/blob/master/data/in/MG/BeloHorizonte/_pk012/make_conf.yaml  ([makefile](https://github.com/AddressForAll/digital-preservation-BR/blob/master/data/in/MG/BeloHorizonte/_pk012/makefile)). variáveis YALM:      subtype:, method,  method_opts

* https://github.com/AddressForAll/digital-preservation-BR/blob/master/data/in/SP/Cabreuva/_pk044/makefile

* comando `docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres' " /tmp/{{{orig_tabname}}} {{{origtabname}}} -nln $(tabname)`

**Comment by ghost** [comment]
O PR https://github.com/digital-guard/preserv-BR/pull/5 atende os três itens dessa issue.
No entanto, não atende a issue https://github.com/AddressForAll/digital-preservation-BR/issues/18.

Nessa issue o comando é, considerando a variável orig_ext:
docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres' " "/tmp/{{orig_filename}}{{orig_ext}}" {{{orig_tabname}}} -nln $(tabname)

Na issue subsequente, https://github.com/AddressForAll/digital-preservation-BR/issues/18, o comando desconsidera orig_ext:
docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres' " /tmp/{{{orig_tabname}}} {{{origtabname}}} -nln $(tabname)

**Comment by crebollobr** [comment]
A variavel deve ser orig_tabname,
origtabname foi um erro de digitação

**Comment by ghost** [comment]
Ok. Mas não era bem isso minha dúvida.

Essa situação: /tmp/{{{orig_tabname}}} {{{origtabname}}}

Engloba essa situação: /tmp/{{orig_filename}}{{orig_ext}} {{{origtabname}}}

Ou são situações disjuntas e para cada uma delas a variável _method_ no arquivo yaml terá valores diferentes para cada uma delas?

**Comment by crebollobr** [comment]
Essa é a proposta da issue,
exemplos
orig_ext: .TAB
orig_ext: .gpkg
orig_ext: .xls

orig_ext = .TAB

Funcionam para extenções diferentes com o mesmo template.
O ogr2ogr trabalha com muitos formatos

**Comment by ppKrauss** [comment]
restaria  padronizar, ver [Wikipedia em inglês](https://en.wikipedia.org/wiki/Comma-separated_values):

* como extensão **.csv** é com virgula. `orig_ext: .csv` seria esperado virgula  
* ....então **csv-pt** seria com ";" (para locales da lang=portugues)
* como  **.tsv** é "tab separated value", e o nome oficial da extensão é `.tsv` (não tab!) então usar `orig_ext: .tsv` para esse caso

Importante lembrar: o padrão textual é UTF-8, qualquer outra coisa precisa ser convertida.

**Comment by 0e1** [comment]
A situação descrita está implementada.
Utilizar no respectivo layer:
```
method: ogr2ogr
orig_ext: .extensão
```
para .xlsx usar
```
method:csv2shp
orig_ext: .xlsx
method_opts: indicar a planilha com -s [0-9], se necessário.
```

**Comment by ppKrauss** [comment]
@0e1 e @crebollobr precisamos criar um "guia rápido do YAML" com link para os exemplos de caso... Por exemplo depois de explicar `method_opts: -D`   pode ilustrar com  [esse caso pk003](https://github.com/digital-guard/preserv-CO/blob/main/data/_pk003/make_conf.yaml).

* a primeira versão vai ser em portugues, em https://github.com/digital-guard/preserv/tree/main/docs/pt
* o primeiro rascunho com todos nós escrevendo livremente dicas e lembretes pode ser em https://github.com/digital-guard/preserv/wiki/Guia-do-make_conf
