### ISSUE TITLE
Itu e Osasco

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/LIXO-digital-preservation-BR#18]
Vai precisar alterar mais coisas que o esperado.
 
- ele tem ogr2ogr junto com shapefile
- No comando 
 
docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres'     " /tmp/OpenStreetMap.gdb {{{orig_tabname}}} -nln $(tabname)
 
ele não usa o nome OpenStreetMap.gdb
 
poderia ser 
 
docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres'     " /tmp/{{{orig_tabname}}}  {{{origtabname}}} -nln $(tabname)
 
mais uma variável

**Comment by 0e1** [comment]
Para essa situação usar no respectivo layer:

`method: ogrWshp`
