### ISSUE TITLE
Osasco

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/LIXO-digital-preservation-BR#23]
Arquivo GPKG

**Comment by 0e1** [comment]
O arquivo `make_conf.yaml` não está disponível em [_pk026](https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Osasco/_pk026), então não testei.

Porem, a combinação, no layer, deve funcionar:
```
method: ogr2ogr
orig_ext: .gpkg
```

**Comment by ppKrauss** [comment]
@crebollobr ,  resolvido?  atenção que agora usamos `codec`
