### ISSUE TITLE
PB-João Pessoa - Makefiles

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/LIXO-digital-preservation-BR#24]
Tarefas:
- [ ] PostGIS: Fazer a atribuição do nome de logradouro nos lotes.

**Comment by ppKrauss** [comment]
Carlos preparar make e indicar para o Claiton o que mais falta fazer, aparentemente está sendo solicitado um JOIN ... Todavia JOINs já não são mais parte do "AS IS", teremos um estágio seguinte no Makefile wue roda as limpezas (**duplicados e nulos fora**) e JOINs.

**Comment by IgorEliezer** [comment]
Esta issue está ainda aberta. Fecha?
