### ISSUE TITLE
!!!!DELETANDO ESSE GIT!!!!!

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/LIXO-digital-preservation-BR#25]
A partir do [comit `ea9740` de Aug 6](https://github.com/AddressForAll/digital-preservation-BR/commit/ea974012947b47093b11e856e45a07443c66eb28) ACABOU, NADA MAIS A GRAVAR AQUI.

Claiton, ajuda aqui: conferir o que mais mudaram em  https://github.com/AddressForAll/digital-preservation-BR/commits/master e levar para o novo

**Comment by ghost** [comment]
Alterei os arquivos no repositório novo http://git.digital-guard.org/preserv-BR.

Três alterações:
https://github.com/digital-guard/preserv-BR/commit/271c5f6ea4e109aee117edff82f59702845e6e0a
https://github.com/digital-guard/preserv-BR/commit/e6f2ce8ddd3a122c3551c406dfbb4c067cdfc759
https://github.com/digital-guard/preserv-BR/commit/37a5fbe66834052a169a2ab941d20be3c60adec3

Essas três alterações anteriores foram oriundas dessas alterações no repositório antigo https://github.com/AddressForAll/digital-preservation-BR:
https://github.com/AddressForAll/digital-preservation-BR/commit/c0b3a8547f73f6f0d61d14e28439e5c9e9291155
https://github.com/AddressForAll/digital-preservation-BR/commit/822d3d970a3bf35065363bc1385ba4ffdfc5400e

...

Essa alteração é de 4 de agosto, no entanto ela não consta no repositório novo:
https://github.com/AddressForAll/digital-preservation-BR/commit/83885fd21965f12a44bde9aa5d3b00601c4b46ac
Essa alteração de url feita nesse commit deve constar no repositório novo?

**Comment by ppKrauss** [comment]
@crebollobr  tudo certo, podemos DELETAR esse git aqui?

**Comment by ppKrauss** [comment]
A decisão por hora é manter até fecharmos ou transferirmos as *issues*.

PS: @cchness , o repositório novo não precisa dos "commits errados", só dos certos, podendo ser o commit final.

**Comment by fititnt** [comment]
> A decisão por hora é manter até fecharmos ou transferirmos as _issues_.
> 
> PS: @cchness , o repositório novo não precisa dos "commits errados", só dos certos, podendo ser o commit final.

Só para avisar, existe uma alternativa também a remover. O GitHub tem opção "archive" <https://docs.github.com/pt/repositories/archiving-a-github-repository>.
