### ISSUE TITLE
Geracao dos makefiles de traducao dos READMEs de cada _preservation

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/LIXO-digital-preservation-BR#6]
Na submissao via Eclusa os arquivos a serem preservados ficam na pasta `_preservation`, onde a descricao humana do que fazer se encontra em arquivo `README.md`, e as instrucoes computacionais (traducao da descricao humana) em `makefile`.
Dentre os pacotes com README ja disponivel, os seguintes foram eleitos, nesta ordem, por Thierry e Igor:

# Três Cidades Pioloto
* BR-RS-PortoAlegre
   * Numeração predial ( Carlos OK )
   * Eixos ( Carlos OK )
   * Bairros ( Carlos OK )
* BR-SP-Cabreuva
* BR-PR-PatoBranco (material está na pasta 'tratamento')

# Cidades candidatas para processamento
## Sem tarefas
* BR-MG-BeloHorizonte
   * CSV ( TODO Converter csv para postgres - Carlos )
* BR-MG-Contagem

## Com tarefas
* BR-PR-Curitiba
* BR-MS-CampoGrande
* BR-PR-Cascavel
* BR-SP-Piracicaba
* BR-SP-RibeiraoPreto
* BR-SP-Atibaia

# IBGE Face de Quadras
* BR/_pk053/

# Não fazer (interno do OSM e A4A)
* BR-PR-SaoJosePinhais
* BR-ES-Serra

**Comment by ppKrauss** [comment]
Situacao hoje dos makefiles, conforme `locate _preservation/makefile` na eclusa:
```
/home/igor/BR-MG-BeloHorizonte/_pk012/_preservation/makefile
/home/igor/BR-MS-CampoGrande/_pk037/_preservation/makefile
/home/igor/BR-PR-Curitiba/_pk002/_preservation/makefile
/home/igor/BR-RS-PortoAlegre/_pk027/_preservation/makefile
/home/igor/BR-SP-Cabreuva/_pk044/_preservation/makefile
```

**Comment by ThierryAJean** [comment]
Igor prepararou 44 do pacote n 1. Destes 30 foram revisados. Carlos recebe junto com Peter, porem o 1ro template não funcionou. Estão refazendo

**Comment by ThierryAJean** [comment]
CArlos e Peter a se reunir hoje a noite sobre isto.

**Comment by ThierryAJean** [comment]
Carlos esperando template do Peter.

**Comment by ThierryAJean** [comment]
Depois de problemas iniciais, se automatizou a geração de Makefiles a partir dos Readme preparados pelo Igor. Vamos fazer isto para 20 cidades e entregar no Github na forma de "dados filtrados" em um BD que vai permitir contar elementos etc...

**Comment by ThierryAJean** [comment]
@crebollobr vai continuar e priorizar esta semana.

**Comment by ThierryAJean** [comment]
Isto tem que ser resolvido em relatório de API par o "mundo" poder ver.
